### ISSUE TITLE
Any luck on apple silicon ?

### ISSUE THREAD

**Issue by ceberly** [AdaCore/gnat-llvm#24]
I imagine i'm not the only one trying this, so, has anyone been able to build for llvm on an apple m1? 

I've tried a couple things like using gcc built for the m1 and using the GNAT community edition for mac x86_64 as a bootstrap. None of them seem to work.

The most promising (i think) has been to try this: 
`gnat-llvm % CC=/Users/chris/opt/GNAT/2020/bin/gcc CXX=/Users/chris/opt/GNAT/2020/bin/g++ make -j32`

which runs for awhile and then bails on a linking step because it looks like it built x86_64 objects instead of an aarch64

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/99014/153440480-b011a52a-86a1-4d75-9a6d-f3c18aca2fda.png">

Thanks! this project has so much potential, i would love if I could get it working on my laptop...

**Comment by ArnaudCharlet** [comment]
We are not aware of anyone having tried/succeeded yet in building GNAT LLVM for apple M1. I guess you'll need to first build a x86_64 GNAT LLVM since this is what your base GNAT compiler knows and then use this GNAT LLVM to build a new GNAT LLVM which targets arm by default. Note that GNAT LLVM is able to bootstrap, meaning that it's capable of building itself, so you should be able to replace GNAT/GCC with GNAT LLVM as your base compiler. Good luck and let us (or anyone else) know how this goes!

**Comment by ceberly** [comment]
thanks, i'll give this a shot!

**Comment by ceberly** [comment]
Actually this might be a GCC issue still, anyway im a bit stumped but maybe somebody has hit this...

**Comment by ArnaudCharlet** [comment]
That's indeed because your base GNAT compiler is too old for your GNAT sources. Using a more recent GNAT on mac os via a alire (https://alire.ada.dev/) should get you further and give you more work around options.

**Comment by ArnaudCharlet** [comment]
Alternatively you could use a script and change all uses of [] by () in libgnat/ to get you past this step. Once you have a recent gnat llvm, youcan revert this temp change.
