### ISSUE TITLE
GNAT-LLVM build failure

### ISSUE THREAD

**Issue by Alex-Gamper** [AdaCore/gnat-llvm#32]
Hi AdaCore

The current master branch fails to build, the following error occurs, this appears to be related to change.
"Avoid infinite recursion for superflat test and protect and add test" (8088e0c) on 20th Jan

gnatllvm-arrays-create.adb:120:39: error: "Cannot_Be_Superflat" is undefined (more references follow)
compilation of gnatllvm-arrays-create.adb failed

Alex

**Comment by ArnaudCharlet** [comment]
Thank you for the report.

Indeed, the change you mention requires a corresponding change in GNAT which has not been merged yet at gcc.gnu.org since GCC is in stage 4 currently. You will need to use the commit just before this one for the time being, until GCC enters stage 1 again and merges resume.
